# codemagic.yaml

workflows:
  unsigned-ipa-build-ios26-1:
    name: Unsigned iOS IPA Build (Xcode 26.1)
    
    instance_type: mac_mini_m1
    
    environment:
      xcode: 26.1 
      flutter: stable
      cocoapods: default
      vars:
        XCODE_SCHEME: "Runner"
        OUTPUT_DIR: "$CM_BUILD_DIR/build/ipa_output"
        ARCHIVE_PATH: "$CM_BUILD_DIR/build/ios/manual_archive/$XCODE_SCHEME.xcarchive"
    
    scripts:
      - name: Install Dependencies (Flutter and Pods)
        script: |
          echo "Starting dependency installation..."
          flutter clean
          flutter pub get
          cd ios
          pod install --repo-update
          
      - name: 1. Build the App and Create the .xcarchive
        script: |
          echo "Building .xcarchive with codesigning explicitly disabled..."
          mkdir -p $(dirname $ARCHIVE_PATH)
          
          xcodebuild archive \
            -workspace ios/Runner.xcworkspace \
            -scheme $XCODE_SCHEME \
            -configuration Release \
            -archivePath $ARCHIVE_PATH \
            -sdk iphoneos \
            CODE_SIGNING_ALLOWED=NO \
            CODE_SIGN_IDENTITY="" \
            PROVISIONING_PROFILE_SPECIFIER=""
          
      - name: 2. Manually Package Unsigned IPA from Archive
        script: |
          echo "Bypassing xcodebuild export and manually packaging the IPA..."
          
          APP_NAME="Runner.app"
          
          # 1. Create the final output directory
          mkdir -p $OUTPUT_DIR
          
          # 2. Define the directory that holds the final app bundle inside the archive
          APP_BUNDLE_PATH="$ARCHIVE_PATH/Products/Applications/$APP_NAME"
          
          # 3. Create the 'Payload' directory (required structure for an IPA)
          mkdir -p Payload
          
          # 4. Copy the app bundle into the 'Payload' directory
          if [ -d "$APP_BUNDLE_PATH" ]; then
              cp -R "$APP_BUNDLE_PATH" Payload/
              
              # 5. ZIP the 'Payload' directory to create the IPA file
              cd Payload/..
              zip -r "$OUTPUT_DIR/HiAnime.ipa" Payload
              
              echo "✅ Successfully created unsigned IPA at $OUTPUT_DIR/HiAnime.ipa"
              
          else
              echo "🚨 ERROR: App bundle not found at $APP_BUNDLE_PATH"
              exit 1
          fi
          
    artifacts:
      # The final unsigned IPA will be found here
      - $OUTPUT_DIR/*.ipa
      - /tmp/xcode_build/*.log
